-- Report B: LEFT JOIN of employees and tickets, selecting both COUNT(*) and COUNT(t.ticket_id) per employee.
-- Returns all 12 employees.
-- Explanation for Priya Das (emp_id = 12): COUNT(*) counts total group rows (including the single NULL-padded row generated by the unmatched LEFT JOIN, returning 1), whereas COUNT(t.ticket_id) evaluates only non-NULL ticket_id values (returning 0).

SELECT 
    e.emp_id, 
    e.name, 
    e.department, 
    COUNT(*) AS total_rows, 
    COUNT(t.ticket_id) AS ticket_count
FROM employees e
LEFT JOIN tickets t ON e.emp_id = t.raised_by
GROUP BY e.emp_id, e.name, e.department
ORDER BY e.emp_id;
